Configure network interaction for web interface

diff --git a/trembita-1-22-6-ss/templates/trembita-disk-init-job.yaml b/trembita-1-22-6-ss/templates/trembita-disk-init-job.yaml
--- a/trembita-1-22-6-ss/templates/trembita-disk-init-job.yaml
+++ b/trembita-1-22-6-ss/templates/trembita-disk-init-job.yaml
@@ -1,3 +1,4 @@
+{{- if .Values.trembita_config.sharedVolumes}}
 apiVersion: batch/v1
 kind: Job
 metadata:
@@ -17,34 +18,33 @@ spec:
           imagePullPolicy: IfNotPresent
           args:
             - |
-{{/*              set -x*/}}
-{{/*              echo "[INFO] Starting init container for {{ $name }}"*/}}
-{{/*              if [ -d "{{ $cfg.mountPath }}" ]; then*/}}
-{{/*                cp -rp {{ $cfg.mountPath }}/* /mnt/target/ || true*/}}
-{{/*                echo "[INFO] Done copying {{ $cfg.mountPath }} to /mnt/target/"*/}}
-{{/*                uid_gid=$(stat -c '%u:%g' {{ $cfg.mountPath }})*/}}
-{{/*                mode=$(stat -c '%a' {{ $cfg.mountPath }})*/}}
-{{/*                echo "[INFO] Changing ownership of /mnt/target/ to $uid_gid"*/}}
-{{/*                chown "$uid_gid" /mnt/target/*/}}
-{{/*                echo "[INFO] Setting permissions of /mnt/target/ to $mode"*/}}
-{{/*                chmod "$mode" /mnt/target/*/}}
-{{/*              else*/}}
-{{/*                echo "[WARN] Source directory {{ $cfg.mountPath }} not found"*/}}
-{{/*              fi*/}}
-          {{- if .Values.trembita_config.sharedVolumes}}
+              set -x
+              {{- range $name, $cfg := .Values.trembita_config.sharedVolumes }}
+              echo "[INFO] Starting init container for {{ $name }}"
+              if [ -d "{{ $cfg.mountPath }}" ]; then
+                cp -rp {{ $cfg.mountPath }}/* /mnt/target/ || true
+                echo "[INFO] Done copying {{ $cfg.mountPath }} to /mnt/target/"
+                uid_gid=$(stat -c '%u:%g' {{ $cfg.mountPath }})
+                mode=$(stat -c '%a' {{ $cfg.mountPath }})
+                echo "[INFO] Changing ownership of /mnt/target/ to $uid_gid"
+                chown "$uid_gid" /mnt/target/
+                echo "[INFO] Setting permissions of /mnt/target/ to $mode"
+                chmod "$mode" /mnt/target/
+              else
+                echo "[WARN] Source directory {{ $cfg.mountPath }} not found"
+              fi
+              {{- end }}
           volumeMounts:
             {{- range $name, $cfg := .Values.trembita_config.sharedVolumes }}
             - name: {{ $name }}-volume
               mountPath: /mnt/target-{{ $name }}-path
             {{- end}}
-          {{- end}}
-      {{- if .Values.trembita_config.sharedVolumes}}
       volumes:
-       {{- range $name, $cfg := .Values.trembita_config.sharedVolumes }}
-       {{- if $cfg.enabled }}
+      {{- range $name, $cfg := .Values.trembita_config.sharedVolumes }}
+      {{- if $cfg.enabled }}
         - name: {{ $name }}-volume
           persistentVolumeClaim:
             claimName: {{ printf "%s-%s" (include "trembita-1-22-6-ss.fullname" $) $name }}
       {{- end }}
       {{- end }}
-      {{- end }}
+{{- end }}
